// <auto-generated />
using System;
using Famick.HomeManagement.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Famick.HomeManagement.Infrastructure.Migrations
{
    [DbContext(typeof(HomeManagementDbContext))]
    [Migration("20260101202055_AddProductUrlToProductStoreMetadata")]
    partial class AddProductUrlToProductStoreMetadata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Famick.HomeManagement.Domain.Entities.Chore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssignmentConfig")
                        .HasColumnType("text")
                        .HasColumnName("assignment_config");

                    b.Property<string>("AssignmentType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("assignment_type");

                    b.Property<short>("ConsumeProductOnExecution")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("consume_product_on_execution");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid?>("NextExecutionAssignedToUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("next_execution_assigned_to_user_id");

                    b.Property<int?>("PeriodDays")
                        .HasColumnType("integer")
                        .HasColumnName("period_days");

                    b.Property<string>("PeriodType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("period_type");

                    b.Property<decimal?>("ProductAmount")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("product_amount");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<short>("Rollover")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("rollover");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<short>("TrackDateOnly")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("track_date_only");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("NextExecutionAssignedToUserId");

                    b.HasIndex("ProductId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_chores_tenant_id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_chores_tenant_name");

                    b.ToTable("chores", (string)null);
                });

            modelBuilder.Entity("Famick.HomeManagement.Domain.Entities.ChoreLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChoreId")
                        .HasColumnType("uuid")
                        .HasColumnName("chore_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("DoneByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("done_by_user_id");

                    b.Property<DateTime?>("ScheduledExecutionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_execution_time");

                    b.Property<short>("Skipped")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("skipped");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("TrackedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tracked_time");

                    b.Property<short>("Undone")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("undone");

                    b.Property<DateTime?>("UndoneTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("undone_timestamp");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("ChoreId")
                        .HasDatabaseName("ix_chores_log_chore_id");

                    b.HasIndex("DoneByUserId")
                        .HasDatabaseName("ix_chores_log_done_by_user_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_chores_log_tenant_id");

                    b.ToTable("chores_log", (string)null);
                });

            modelBuilder.Entity("Famick.HomeManagement.Domain.Entities.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique();

                    b.ToTable("locations", (string)null);
                });

            modelBuilder.Entity("Famick.HomeManagement.Domain.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("permissions", (string)null);
                });

            modelBuilder.Entity("Famick.HomeManagement.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("DefaultBestBeforeDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("MinStockAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid?>("ProductGroupId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("QuantityUnitFactorPurchaseToStock")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasDefaultValue(1.0m);

                    b.Property<Guid>("QuantityUnitIdPurchase")
                        .HasColumnType("uuid");

                    b.Property<Guid>("QuantityUnitIdStock")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ServingSize")
                        .HasColumnType("numeric");

                    b.Property<string>("ServingUnit")
                        .HasColumnType("text");

                    b.Property<decimal?>("ServingsPerContainer")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("ShoppingLocationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("ProductGroupId");

                    b.HasIndex("QuantityUnitIdPurchase");

                    b.HasIndex("QuantityUnitIdStock");

                    b.HasIndex("ShoppingLocationId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "Name");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("Famick.HomeManagement.Domain.Entities.ProductBarcode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "Barcode")
                        .IsUnique();

                    b.ToTable("product_barcodes", (string)null);
                });

            modelBuilder.Entity("Famick.HomeManagement.Domain.Entities.ProductGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_product_groups_tenant_id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_product_groups_tenant_name");

                    b.ToTable("product_groups", (string)null);
                });

            modelBuilder.Entity("Famick.HomeManagement.Domain.Entities.ProductImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ExternalSource")
                        .HasColumnType("text");

                    b.Property<string>("ExternalThumbnailUrl")
                        .HasColumnType("text");

                    b.Property<string>("ExternalUrl")
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "ProductId");

                    b.ToTable("product_images", (string)null);
                });

            modelBuilder.Entity("Famick.HomeManagement.Domain.Entities.ProductNutrition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("AddedSugars")
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("added_sugars");

                    b.Property<string>("BrandName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("brand_name");

                    b.Property<string>("BrandOwner")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("brand_owner");

                    b.Property<decimal?>("Calcium")
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("calcium");

                    b.Property<decimal?>("Calories")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("calories");

                    b.Property<decimal?>("Cholesterol")
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("cholesterol");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DataSource")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("data_source");

                    b.Property<decimal?>("DietaryFiber")
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("dietary_fiber");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_id");

                    b.Property<decimal?>("Folate")
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("folate");

                    b.Property<string>("Ingredients")
                        .HasColumnType("text")
                        .HasColumnName("ingredients");

                    b.Property<decimal?>("Iron")
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("iron");

                    b.Property<DateTime>("LastUpdatedFromSource")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_from_source");

                    b.Property<decimal?>("Magnesium")
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("magnesium");

                    b.Property<decimal?>("Niacin")
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("niacin");

                    b.Property<decimal?>("Phosphorus")
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("phosphorus");

                    b.Property<decimal?>("Potassium")
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("potassium");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<decimal?>("Protein")
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("protein");

                    b.Property<decimal?>("Riboflavin")
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("riboflavin");

                    b.Property<decimal?>("SaturatedFat")
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("saturated_fat");

                    b.Property<decimal?>("ServingSize")
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("serving_size");

                    b.Property<string>("ServingSizeDescription")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("serving_size_description");

                    b.Property<string>("ServingUnit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("serving_unit");

                    b.Property<decimal?>("ServingsPerContainer")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Sodium")
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("sodium");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal?>("Thiamin")
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("thiamin");

                    b.Property<decimal?>("TotalCarbohydrates")
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("total_carbohydrates");

                    b.Property<decimal?>("TotalFat")
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("total_fat");

                    b.Property<decimal?>("TotalSugars")
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("total_sugars");

                    b.Property<decimal?>("TransFat")
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("trans_fat");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal?>("VitaminA")
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("vitamin_a");

                    b.Property<decimal?>("VitaminB12")
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("vitamin_b12");

                    b.Property<decimal?>("VitaminB6")
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("vitamin_b6");

                    b.Property<decimal?>("VitaminC")
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("vitamin_c");

                    b.Property<decimal?>("VitaminD")
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("vitamin_d");

                    b.Property<decimal?>("VitaminE")
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("vitamin_e");

                    b.Property<decimal?>("VitaminK")
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("vitamin_k");

                    b.Property<decimal?>("Zinc")
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("zinc");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique()
                        .HasDatabaseName("ux_product_nutrition_product_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_product_nutrition_tenant_id");

                    b.HasIndex("DataSource", "ExternalId")
                        .HasDatabaseName("ix_product_nutrition_data_source_external_id");

                    b.ToTable("product_nutrition", (string)null);
                });

            modelBuilder.Entity("Famick.HomeManagement.Domain.Entities.ProductStoreMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Aisle")
                        .HasColumnType("character varying(50)")
                        .HasColumnName("aisle");

                    b.Property<DateTime?>("AvailabilityCheckedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("availability_checked_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Department")
                        .HasColumnType("character varying(100)")
                        .HasColumnName("department");

                    b.Property<string>("ExternalProductId")
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_product_id");

                    b.Property<bool?>("InStock")
                        .HasColumnType("boolean")
                        .HasColumnName("in_stock");

                    b.Property<decimal?>("LastKnownPrice")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("last_known_price");

                    b.Property<string>("PriceUnit")
                        .HasColumnType("character varying(50)")
                        .HasColumnName("price_unit");

                    b.Property<DateTime?>("PriceUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("price_updated_at");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductUrl")
                        .HasColumnType("text");

                    b.Property<string>("Shelf")
                        .HasColumnType("character varying(50)")
                        .HasColumnName("shelf");

                    b.Property<Guid>("ShoppingLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("shopping_location_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ShoppingLocationId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_product_store_metadata_tenant_id");

                    b.HasIndex("TenantId", "ProductId")
                        .HasDatabaseName("ix_product_store_metadata_tenant_product");

                    b.HasIndex("TenantId", "ShoppingLocationId")
                        .HasDatabaseName("ix_product_store_metadata_tenant_location");

                    b.HasIndex("TenantId", "ProductId", "ShoppingLocationId")
                        .IsUnique()
                        .HasDatabaseName("ux_product_store_metadata_product_location");

                    b.ToTable("product_store_metadata", (string)null);
                });

            modelBuilder.Entity("Famick.HomeManagement.Domain.Entities.QuantityUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NamePlural")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique();

                    b.ToTable("quantity_units", (string)null);
                });

            modelBuilder.Entity("Famick.HomeManagement.Domain.Entities.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_recipes_tenant_id");

                    b.HasIndex("TenantId", "Name")
                        .HasDatabaseName("ix_recipes_tenant_name");

                    b.ToTable("recipes", (string)null);
                });

            modelBuilder.Entity("Famick.HomeManagement.Domain.Entities.RecipeNesting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("IncludesRecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("includes_recipe_id");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipe_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("IncludesRecipeId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_recipes_nestings_tenant_id");

                    b.HasIndex("RecipeId", "IncludesRecipeId")
                        .IsUnique()
                        .HasDatabaseName("ux_recipes_nestings_recipe_includes");

                    b.ToTable("recipes_nestings", (string)null);
                });

            modelBuilder.Entity("Famick.HomeManagement.Domain.Entities.RecipePosition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,4)")
                        .HasDefaultValue(0m)
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("IngredientGroup")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("ingredient_group");

                    b.Property<short>("NotCheckStockFulfillment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("not_check_stock_fulfillment");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<short>("OnlyCheckSingleUnitInStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("only_check_single_unit_in_stock");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<Guid?>("QuantityUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("qu_id");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipe_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_recipes_pos_product_id");

                    b.HasIndex("QuantityUnitId");

                    b.HasIndex("RecipeId")
                        .HasDatabaseName("ix_recipes_pos_recipe_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_recipes_pos_tenant_id");

                    b.ToTable("recipes_pos", (string)null);
                });

            modelBuilder.Entity("Famick.HomeManagement.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DeviceInfo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("RememberMe")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("ReplacedByTokenId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TokenHash");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Famick.HomeManagement.Domain.Entities.ShoppingList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_shopping_lists_tenant_id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_shopping_lists_tenant_name");

                    b.ToTable("shopping_lists", (string)null);
                });

            modelBuilder.Entity("Famick.HomeManagement.Domain.Entities.ShoppingListItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,4)")
                        .HasDefaultValue(0m)
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<Guid>("ShoppingListId")
                        .HasColumnType("uuid")
                        .HasColumnName("shopping_list_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_shopping_list_product_id");

                    b.HasIndex("ShoppingListId")
                        .HasDatabaseName("ix_shopping_list_shopping_list_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_shopping_list_tenant_id");

                    b.ToTable("shopping_list", (string)null);
                });

            modelBuilder.Entity("Famick.HomeManagement.Domain.Entities.ShoppingLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ExternalChainId")
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_chain_id");

                    b.Property<string>("ExternalLocationId")
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_location_id");

                    b.Property<string>("IntegrationType")
                        .HasColumnType("character varying(50)")
                        .HasColumnName("integration_type");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("OAuthAccessToken")
                        .HasColumnType("text")
                        .HasColumnName("oauth_access_token");

                    b.Property<string>("OAuthRefreshToken")
                        .HasColumnType("text")
                        .HasColumnName("oauth_refresh_token");

                    b.Property<DateTime?>("OAuthTokenExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("oauth_token_expires_at");

                    b.Property<string>("StoreAddress")
                        .HasColumnType("character varying(500)")
                        .HasColumnName("store_address");

                    b.Property<string>("StorePhone")
                        .HasColumnType("character varying(50)")
                        .HasColumnName("store_phone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_shopping_locations_tenant_id");

                    b.HasIndex("TenantId", "IntegrationType")
                        .HasDatabaseName("ix_shopping_locations_tenant_integration_type");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_shopping_locations_tenant_name");

                    b.ToTable("shopping_locations", (string)null);
                });

            modelBuilder.Entity("Famick.HomeManagement.Domain.Entities.StockEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount");

                    b.Property<DateTime?>("BestBeforeDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("best_before_date");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<bool>("Open")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("open");

                    b.Property<int?>("OpenTrackingMode")
                        .HasColumnType("integer")
                        .HasColumnName("open_tracking_mode");

                    b.Property<DateTime?>("OpenedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_date");

                    b.Property<decimal?>("OriginalAmount")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("original_amount");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("price");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<DateTime>("PurchasedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("purchased_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("ShoppingLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("shopping_location_id");

                    b.Property<string>("StockId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("stock_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("StockId")
                        .HasDatabaseName("ix_stock_stock_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_stock_tenant_id");

                    b.HasIndex("TenantId", "StockId")
                        .IsUnique()
                        .HasDatabaseName("ux_stock_tenant_stock_id");

                    b.HasIndex("ProductId", "Open", "BestBeforeDate", "Amount")
                        .HasDatabaseName("ix_stock_performance1");

                    b.ToTable("stock", (string)null);
                });

            modelBuilder.Entity("Famick.HomeManagement.Domain.Entities.StockLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount");

                    b.Property<DateTime?>("BestBeforeDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("best_before_date");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<DateTime?>("OpenedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_date");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("price");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<DateTime?>("PurchasedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("purchased_date");

                    b.Property<Guid?>("RecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipe_id");

                    b.Property<Guid?>("ShoppingLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("shopping_location_id");

                    b.Property<int>("Spoiled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("spoiled");

                    b.Property<string>("StockId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("stock_id");

                    b.Property<Guid?>("StockRowId")
                        .HasColumnType("uuid")
                        .HasColumnName("stock_row_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("transaction_id");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("transaction_type");

                    b.Property<bool>("Undone")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("undone");

                    b.Property<DateTime?>("UndoneTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("undone_timestamp");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("UsedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_date");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_stock_log_correlation_id");

                    b.HasIndex("LocationId");

                    b.HasIndex("StockRowId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_stock_log_tenant_id");

                    b.HasIndex("TransactionId")
                        .HasDatabaseName("ix_stock_log_transaction_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_stock_log_user_id");

                    b.HasIndex("StockId", "TransactionType", "Amount")
                        .HasDatabaseName("ix_stock_log_performance1");

                    b.HasIndex("ProductId", "BestBeforeDate", "PurchasedDate", "TransactionType", "StockId", "Undone")
                        .HasDatabaseName("ix_stock_log_performance2");

                    b.ToTable("stock_log", (string)null);
                });

            modelBuilder.Entity("Famick.HomeManagement.Domain.Entities.TenantIntegrationToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessToken")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastRefreshedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PluginId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<bool>("RequiresReauth")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("PluginId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "PluginId")
                        .IsUnique();

                    b.ToTable("TenantIntegrationTokens");
                });

            modelBuilder.Entity("Famick.HomeManagement.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique();

                    b.HasIndex("TenantId", "Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Famick.HomeManagement.Domain.Entities.UserPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId");

                    b.HasIndex("TenantId", "UserId", "PermissionId")
                        .IsUnique();

                    b.ToTable("user_permissions", (string)null);
                });

            modelBuilder.Entity("Famick.HomeManagement.Domain.Entities.Chore", b =>
                {
                    b.HasOne("Famick.HomeManagement.Domain.Entities.User", "NextExecutionAssignedToUser")
                        .WithMany()
                        .HasForeignKey("NextExecutionAssignedToUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_chores_users");

                    b.HasOne("Famick.HomeManagement.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_chores_products");

                    b.Navigation("NextExecutionAssignedToUser");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Famick.HomeManagement.Domain.Entities.ChoreLog", b =>
                {
                    b.HasOne("Famick.HomeManagement.Domain.Entities.Chore", "Chore")
                        .WithMany("LogEntries")
                        .HasForeignKey("ChoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chores_log_chores");

                    b.HasOne("Famick.HomeManagement.Domain.Entities.User", "DoneByUser")
                        .WithMany()
                        .HasForeignKey("DoneByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_chores_log_users");

                    b.Navigation("Chore");

                    b.Navigation("DoneByUser");
                });

            modelBuilder.Entity("Famick.HomeManagement.Domain.Entities.Product", b =>
                {
                    b.HasOne("Famick.HomeManagement.Domain.Entities.Location", "Location")
                        .WithMany("Products")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Famick.HomeManagement.Domain.Entities.ProductGroup", "ProductGroup")
                        .WithMany("Products")
                        .HasForeignKey("ProductGroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Famick.HomeManagement.Domain.Entities.QuantityUnit", "QuantityUnitPurchase")
                        .WithMany("ProductsWithPurchaseUnit")
                        .HasForeignKey("QuantityUnitIdPurchase")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Famick.HomeManagement.Domain.Entities.QuantityUnit", "QuantityUnitStock")
                        .WithMany("ProductsWithStockUnit")
                        .HasForeignKey("QuantityUnitIdStock")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Famick.HomeManagement.Domain.Entities.ShoppingLocation", "ShoppingLocation")
                        .WithMany("Products")
                        .HasForeignKey("ShoppingLocationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Location");

                    b.Navigation("ProductGroup");

                    b.Navigation("QuantityUnitPurchase");

                    b.Navigation("QuantityUnitStock");

                    b.Navigation("ShoppingLocation");
                });

            modelBuilder.Entity("Famick.HomeManagement.Domain.Entities.ProductBarcode", b =>
                {
                    b.HasOne("Famick.HomeManagement.Domain.Entities.Product", "Product")
                        .WithMany("Barcodes")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Famick.HomeManagement.Domain.Entities.ProductImage", b =>
                {
                    b.HasOne("Famick.HomeManagement.Domain.Entities.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Famick.HomeManagement.Domain.Entities.ProductNutrition", b =>
                {
                    b.HasOne("Famick.HomeManagement.Domain.Entities.Product", "Product")
                        .WithOne("Nutrition")
                        .HasForeignKey("Famick.HomeManagement.Domain.Entities.ProductNutrition", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Famick.HomeManagement.Domain.Entities.ProductStoreMetadata", b =>
                {
                    b.HasOne("Famick.HomeManagement.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Famick.HomeManagement.Domain.Entities.ShoppingLocation", "ShoppingLocation")
                        .WithMany("ProductStoreMetadata")
                        .HasForeignKey("ShoppingLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ShoppingLocation");
                });

            modelBuilder.Entity("Famick.HomeManagement.Domain.Entities.RecipeNesting", b =>
                {
                    b.HasOne("Famick.HomeManagement.Domain.Entities.Recipe", "IncludedRecipe")
                        .WithMany("ParentRecipes")
                        .HasForeignKey("IncludesRecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipes_nestings_includes_recipe_id");

                    b.HasOne("Famick.HomeManagement.Domain.Entities.Recipe", "Recipe")
                        .WithMany("NestedRecipes")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipes_nestings_recipe_id");

                    b.Navigation("IncludedRecipe");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Famick.HomeManagement.Domain.Entities.RecipePosition", b =>
                {
                    b.HasOne("Famick.HomeManagement.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_recipes_pos_products");

                    b.HasOne("Famick.HomeManagement.Domain.Entities.QuantityUnit", "QuantityUnit")
                        .WithMany()
                        .HasForeignKey("QuantityUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_recipes_pos_quantity_units");

                    b.HasOne("Famick.HomeManagement.Domain.Entities.Recipe", "Recipe")
                        .WithMany("Positions")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipes_pos_recipes");

                    b.Navigation("Product");

                    b.Navigation("QuantityUnit");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Famick.HomeManagement.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Famick.HomeManagement.Domain.Entities.RefreshToken", "ReplacedByToken")
                        .WithMany()
                        .HasForeignKey("ReplacedByTokenId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Famick.HomeManagement.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReplacedByToken");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Famick.HomeManagement.Domain.Entities.ShoppingListItem", b =>
                {
                    b.HasOne("Famick.HomeManagement.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_shopping_list_products");

                    b.HasOne("Famick.HomeManagement.Domain.Entities.ShoppingList", "ShoppingList")
                        .WithMany("Items")
                        .HasForeignKey("ShoppingListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_shopping_list_shopping_lists");

                    b.Navigation("Product");

                    b.Navigation("ShoppingList");
                });

            modelBuilder.Entity("Famick.HomeManagement.Domain.Entities.StockEntry", b =>
                {
                    b.HasOne("Famick.HomeManagement.Domain.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_stock_locations");

                    b.HasOne("Famick.HomeManagement.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stock_products");

                    b.Navigation("Location");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Famick.HomeManagement.Domain.Entities.StockLog", b =>
                {
                    b.HasOne("Famick.HomeManagement.Domain.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_stock_log_locations");

                    b.HasOne("Famick.HomeManagement.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stock_log_products");

                    b.HasOne("Famick.HomeManagement.Domain.Entities.StockEntry", "StockRow")
                        .WithMany()
                        .HasForeignKey("StockRowId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_stock_log_stock");

                    b.HasOne("Famick.HomeManagement.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stock_log_users");

                    b.Navigation("Location");

                    b.Navigation("Product");

                    b.Navigation("StockRow");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Famick.HomeManagement.Domain.Entities.UserPermission", b =>
                {
                    b.HasOne("Famick.HomeManagement.Domain.Entities.Permission", "Permission")
                        .WithMany("UserPermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Famick.HomeManagement.Domain.Entities.User", "User")
                        .WithMany("UserPermissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Famick.HomeManagement.Domain.Entities.Chore", b =>
                {
                    b.Navigation("LogEntries");
                });

            modelBuilder.Entity("Famick.HomeManagement.Domain.Entities.Location", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Famick.HomeManagement.Domain.Entities.Permission", b =>
                {
                    b.Navigation("UserPermissions");
                });

            modelBuilder.Entity("Famick.HomeManagement.Domain.Entities.Product", b =>
                {
                    b.Navigation("Barcodes");

                    b.Navigation("Images");

                    b.Navigation("Nutrition");
                });

            modelBuilder.Entity("Famick.HomeManagement.Domain.Entities.ProductGroup", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Famick.HomeManagement.Domain.Entities.QuantityUnit", b =>
                {
                    b.Navigation("ProductsWithPurchaseUnit");

                    b.Navigation("ProductsWithStockUnit");
                });

            modelBuilder.Entity("Famick.HomeManagement.Domain.Entities.Recipe", b =>
                {
                    b.Navigation("NestedRecipes");

                    b.Navigation("ParentRecipes");

                    b.Navigation("Positions");
                });

            modelBuilder.Entity("Famick.HomeManagement.Domain.Entities.ShoppingList", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Famick.HomeManagement.Domain.Entities.ShoppingLocation", b =>
                {
                    b.Navigation("ProductStoreMetadata");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("Famick.HomeManagement.Domain.Entities.User", b =>
                {
                    b.Navigation("UserPermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
